aol_register({
    {
        type = "technology",
        name = "vanilla-technology-nomadic-lifestyle",
        age = "vanilla-age-stone-age",
        level = 0,
        is_root = true,
        order = "1",
        research_time = 3,
        research_effect = {},
        parents = {},
        icon = "__base__/graphics/technology/icons/nomadic-lifestyle.png"
    },
    {
        type = "technology",
        name = "vanilla-technology-tools-1",
        age = "vanilla-age-stone-age",
        level = 0,
        order = "3",
        research_time = 2,
        research_effect = {},
        parents = {"vanilla-technology-nomadic-lifestyle"},
        icon = "__base__/graphics/technology/icons/tools-1.png"
    },
    {
        type = "technology",
        name = "vanilla-technology-fire",
        age = "vanilla-age-stone-age",
        level = 1,
        order = "1",
        research_time = 2,
        research_effect = {},
        parents = {"vanilla-technology-nomadic-lifestyle"},
        icon = "__base__/graphics/technology/icons/fire.png"
    },
    {
        type = "technology",
        name = "vanilla-technology-wall-art",
        age = "vanilla-age-stone-age",
        level = 2,
        order = "1",
        research_time = 3,
        research_effect = {},
        parents = {"vanilla-technology-fire"},
        icon = "__base__/graphics/technology/icons/wall-art.png"
    },
    {
        type = "technology",
        name = "vanilla-technology-speech",
        age = "vanilla-age-stone-age",
        level = 2,
        order = "2",
        research_time = 2,
        research_effect = {},
        parents = {"vanilla-technology-fire"},
        icon = "__base__/graphics/technology/icons/speech.png"
    },
    {
        type = "technology",
        name = "vanilla-technology-meatmaking",
        age = "vanilla-age-stone-age",
        level = 2,
        order = "3",
        research_time = 2,
        research_effect = {},
        parents = {"vanilla-technology-fire"},
        icon = "__base__/graphics/technology/icons/meatmaking.png"
    },
    {
        type = "technology",
        name = "vanilla-technology-armory-1",
        age = "vanilla-age-stone-age",
        level = 2,
        order = "4",
        research_time = 2,
        research_effect = {},
        parents = {"vanilla-technology-tools-1"},
        icon = "__base__/graphics/technology/icons/armory-1.png",
        force_offset = 1,
        count_to_width = false
    },
    {
        type = "technology",
        name = "vanilla-technology-teaching-1",
        age = "vanilla-age-stone-age",
        level = 3,
        order = "1",
        research_time = 2,
        research_effect = {},
        parents = {"vanilla-technology-speech"},
        icon = "__base__/graphics/technology/icons/teaching-1.png"
    },
    {
        type = "technology",
        name = "vanilla-technology-strategy",
        age = "vanilla-age-stone-age",
        level = 3,
        order = "2",
        research_time = 2,
        research_effect = {},
        parents = {"vanilla-technology-speech"},
        icon = "__base__/graphics/technology/icons/strategy.png"
    },
    {
        type = "technology",
        name = "vanilla-technology-tools-2",
        age = "vanilla-age-stone-age",
        level = 3,
        order = "3",
        research_time = 2,
        research_effect = {},
        parents = {"vanilla-technology-tools-1"},
        icon = "__base__/graphics/technology/icons/tools-2.png"
    },
    {
        type = "technology",
        name = "vanilla-technology-teaching-2",
        age = "vanilla-age-stone-age",
        level = 4,
        order = "1",
        research_time = 2,
        research_effect = {},
        parents = {"vanilla-technology-teaching-1", "vanilla-technology-strategy"},
        icon = "__base__/graphics/technology/icons/teaching-2.png"
    },
    {
        type = "technology",
        name = "vanilla-technology-planting",
        age = "vanilla-age-stone-age",
        level = 4,
        order = "2",
        research_time = 2,
        research_effect = {},
        parents = {"vanilla-technology-strategy", "vanilla-technology-meatmaking", "vanilla-technology-tools-2"},
        icon = "__base__/graphics/technology/icons/planting.png"
    },
    {
        type = "technology",
        name = "vanilla-technology-armory-2",
        age = "vanilla-age-stone-age",
        level = 4,
        order = "3",
        research_time = 2,
        research_effect = {},
        parents = {"vanilla-technology-tools-2", "vanilla-technology-armory-1"},
        icon = "__base__/graphics/technology/icons/armory-2.png"
    },
    {
        type = "technology",
        name = "vanilla-technology-roles",
        age = "vanilla-age-stone-age",
        level = 5,
        order = "1",
        research_time = 2,
        research_effect = {},
        parents = {"vanilla-technology-teaching-2"},
        icon = "__base__/graphics/technology/icons/roles.png"
    },
    {
        type = "technology",
        name = "vanilla-technology-farming",
        age = "vanilla-age-stone-age",
        level = 5,
        order = "2",
        research_time = 2,
        research_effect = {},
        parents = {"vanilla-technology-teaching-2", "vanilla-technology-planting"},
        icon = "__base__/graphics/technology/icons/farming.png"
    },
    {
        type = "technology",
        name = "vanilla-technology-grind",
        age = "vanilla-age-stone-age",
        level = 5,
        order = "3",
        research_time = 2,
        research_effect = {},
        parents = {"vanilla-technology-tools-2"},
        icon = "__base__/graphics/technology/icons/grind.png"
    },
    {
        type = "technology",
        name = "vanilla-technology-art",
        age = "vanilla-age-stone-age",
        level = 6,
        order = "1",
        research_time = 2,
        research_effect = {},
        parents = {"vanilla-technology-wall-art"},
        icon = "__base__/graphics/technology/icons/art.png"
    },
    {
        type = "technology",
        name = "vanilla-technology-sedentary-lifestyle",
        age = "vanilla-age-stone-age",
        level = 6,
        order = "2",
        research_time = 2,
        research_effect = {},
        parents = {"vanilla-technology-farming", "vanilla-technology-roles"},
        icon = "__base__/graphics/technology/icons/sedentary-lifestyle.png",
        pass = true
    },
    {
        type = "technology",
        name = "vanilla-technology-tools-3",
        age = "vanilla-age-stone-age",
        level = 6,
        order = "3",
        research_time = 2,
        research_effect = {},
        parents = {"vanilla-technology-grind"},
        icon = "__base__/graphics/technology/icons/tools-3.png"
    },
    {
        type = "technology",
        name = "vanilla-technology-ceramics",
        age = "vanilla-age-stone-age",
        level = 7,
        order = "1",
        research_time = 2,
        research_effect = {},
        parents = {"vanilla-technology-art", "vanilla-technology-tools-3"},
        icon = "__base__/graphics/technology/icons/ceramics.png",
        pass = true
    },
    {
        type = "technology",
        name = "vanilla-technology-armory-3",
        age = "vanilla-age-stone-age",
        level = 7,
        order = "2",
        research_time = 2,
        research_effect = {},
        parents = {"vanilla-technology-armory-2", "vanilla-technology-tools-3"},
        icon = "__base__/graphics/technology/icons/armory-3.png",
        pass = true
    },

    -- Copper age

    {
        type = "technology",
        name = "vanilla-technology-sedentary-lifestyle:pass",
        age = "vanilla-age-copper-age",
        level = 0,
        order = "0",
        research_time = 2,
        research_effect = {},
        parents = {},
        icon = "__base__/graphics/technology/icons/sedentary-lifestyle.png",
        is_root = true
    },
    {
        type = "technology",
        name = "vanilla-technology-ceramics:pass",
        age = "vanilla-age-copper-age",
        level = 0,
        order = "1",
        research_time = 2,
        research_effect = {},
        parents = {},
        icon = "__base__/graphics/technology/icons/ceramics.png",
        is_root = true
    },
    {
        type = "technology",
        name = "vanilla-technology-armory-3:pass",
        age = "vanilla-age-copper-age",
        level = 0,
        order = "2",
        research_time = 2,
        research_effect = {},
        parents = {},
        icon = "__base__/graphics/technology/icons/armory-3.png",
        is_root = true
    },
})