#pragma once

#define AGL_EVENT_MOUSE_PRESSED 0x01
#define AGL_EVENT_MOUSE_MOVED 0x02
#define AGL_EVENT_MOUSE_RELEASED 0x03

#define AGL_EVENT_CHILD_ADDED 0x11
#define AGL_EVENT_BLOCK_RESIZED 0x12
#define AGL_EVENT_BLOCK_MOVED 0x13
#define AGL_EVENT_BLOCK_HOVER_GAINED 0x14
#define AGL_EVENT_BLOCK_HOVER_LOST 0x15
#define AGL_EVENT_BLOCK_FOCUS_GAINED 0x16
#define AGL_EVENT_BLOCK_FOCUS_LOST 0x17
#define AGL_EVENT_TEXT_CHANGED 0x18

#define AGL_EVENT_KEY_PRESSED 0x21
#define AGL_EVENT_KEY_RELEASED 0x22
#define AGL_EVENT_CHAR_INPUT 0x23

#define AGL_MOUSE_NBUTTON_LEFT 1

#define AGL_MOUSE_BBUTTON_PRIMARY 0b1
#define AGL_MOUSE_BBUTTON_SECONDARY 0b10